## What is Bytes & Bites?

Bytes & Bites is a **programming CAFE**, CAFE being an acronym for "_Code Along, Feel Empowered_". It was started in April 2023 as part of a cross institution initiative to support researchers in the domain of programming. There is no specific language focus (both human and machine), but it tends to mostly be Python and R.


>**programming café** /noun/ - a welcoming and
>inclusive space to connect people, share knowledge
>and support researchers in their coding journeys


Bytes & Bites is a monthly meetup, usually in the O|2 building, room 01W08 on the Vrije Universiteit Amsterdam campus. It is a part of the VU software community typically with VULTURE level 2 and 3 talks, workshops, and presentations, though everyone of any level is welcome.

The idea is to provide a welcoming and inclusive space to connect anyone interested in programming with other programmers to help facilitate knowledge sharing and support. We also eat pizza and chat!

If you would like to learn more about Bytes and Bites why not read about previous events on the [events page](../events.qmd) or join us at the next session?  
To find out more about the CAFE initiative read the paper [here](https://zenodo.org/records/8047119).


## Our level system

Not every event is suitable for every programmer. To help people decide if it's the right levl for them we use a level system. Take a look to see where you land and check the events to see which level(s) they are.


**Lvl : 0**

You have a vague idea of what programming is. Perhaps it still feels more like basement dweller or matrix activity to you.

The events at this level are more like sales pitches and should answer the following for you, what is programming, can a code hurt you, how can I automate the boring parts of my life, will a robot ever love? Here you will see examples of how colleagues gained time, kudos, and comradery from programming projects.
  

**Lvl: 1**

You might have just completed a carpentry or online programming course and can just about use the skill transfer to work on a different dataset than the example one. 

Events at this level are more introductionary, a Carpentry or similar course. How to write a basic program to do the most basic tasks a researcher might need to do – open data, filter, make a graph. We explain the mindset of coding to an extent, “how does a computer think?”.
  

**Lvl: 2**

You can code their own projects, use stackoverflow, and might follow a youtuber or two. You know when to use chunks of code you find, but might not yet understand it all.

A level 2 event will teach how to write good, clean code. Topics such as naming conventions, folder structure, lambda functions, doc strings, and code readability are covered here. Additional useful topics at this level would be making a web app and writing a package or exe in order to keep their code accessible. 

  
**Lvl: 3**

You can handle yourself, help others, know a few sites to check for tricks, and you read documentation (to an extent). You know enough to make tools for others that are in regular use and could teach anyone at least something (nobody knows everything).

Level 3 events are the current typical level of Bytes & Bites - talks from internal or external speakers about more advanced topics. These serve more as inspiration, a place where ideas will click into place for the attendees. They will ask insightful questions and share relevant knowledge at the sessions.
  

**Lvl: 4**

You're a long time programmer and are almost beyond writing code at this point. You know the names of more Linux distros than family members. You likely spend most time thinking about the code and directing others than writing code, but the code you write is perfection.

We have looped back around to sales pitches. These should be more about efficiency of code, quality of life changes, and infrastructure discussion. The attendees influence policy and so need to be sold on cutting edge ideas. Expect arguments over seemingly minor topics.

