---
title: "Bytes & Bites"
date: "04/04/2023"
description: "16-18 @ O|2 building, room 01W08"
---

Theme: Visualizations

[Register](https://vu-nl.libcal.com/event/4023149)

### General tips on visualization
- [Introduction to data visualization](https://carpentries-incubator.github.io/intro-data-viz/)
- [Examples of bad graphs in papers](https://www.biostat.wisc.edu/~kbroman/topten_worstgraphs/)

### Datasets
- [Datasets about Dutch society by the CBS](https://opendata.cbs.nl/statline/#/CBS/en/navigatieScherm/thema)
- [Public datasets from different domains](https://github.com/awesomedata/awesome-public-datasets)
- [Datasets from data science community Kaggle](https://www.kaggle.com/datasets)

### Examples of programming resources

##### R
- [Chapter in data carpentries workshop](https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html)
- [Introduction to ggplot](https://stulp.gmw.rug.nl/ggplotworkshop/ggplotquick.html)

##### Python
- [Carpentries workshop on how to create interactive visualizations](https://carpentries-incubator.github.io/python-interactive-data-visualizations/)
- [Notebooks to play with some examples](https://mybinder.org/v2/gh/jgarciab/workshop_data_viz/HEAD)
- [A collection of Jupyter notebooks for geoscientists](https://github.com/pinshuai/jupyter-for-geoscience)
- [Chapter in data carpentries workshop](https://datacarpentry.org/python-ecology-lesson/08-putting-it-all-together/index.html)

##### Matlab
- [Overview of different plot options](https://nl.mathworks.com/help/matlab/creating_plots/types-of-matlab-plots.html)
- [Tutorial for plotting and graphics](https://www.tutorialspoint.com/matlab/matlab_plotting.htm)
- [Tutorial to visualizations (including 3d)](https://www.bu.edu/tech/support/research/training-consulting/online-tutorials/visualization-with-matlab/)

##### HPC (any language)
- [Academic training for HPC users](https://hpc-portal.eu/search/node?keys=visualization)
- [Work in progress, examples and tips](https://bazis.readthedocs.io/)
