---
title: "Bytes & Bites - Documentation and Good Practices"
date: "03/05/2024"
description: "16-18 @ O|2 building, room 01W08"
---

Theme: Documentation and Good Practices

This edition of Bytes & Bites will focus on making your life and work easier in the long-term. We will talk about very practical first steps you can do right away to organize your code in a better way, for example by documenting your code for yourself, your collaborators, and potential reviewers and third-party users. 

We will run this event slightly different than usual and make it as interactive and fun as possible. Practice your Lego skills and join us on March 5th!

There is only limited time to give you a good overview and get you started. If you are interested in learning more about best software management practices, please consider taking part in the CodeRefinery in March: https://coderefinery.github.io/2024-03-12-workshop/

The CodeRefinery workshop is online and covers the following topics:

* collaboration;
* resolving conflicts;
* social coding;
* documentation;
* testing;
* modular coding;
* Git for version control.

[Register](https://vu-nl.libcal.com/event/4186166)
