---
title: "Bytes & Bites - Data Visualisation Coding Tutorial"
date: "06/18/2024"
description: "16-18 @ O|2 building, event room on ground floor"
---

Theme: A Data Visualisation Coding Tutorial in R and Python.

Programming beginners in R ans/or Python will be empowered to harness basic data analysis tools essential for Neuroscientific research and beyond. We will provide basic practical insights and hands-on experience to enhance your research analysis capabilities. Don't miss this opportunity to enhance your skill set and network with fellow enthusiasts.

If you are a novice and wouldn’t want to miss some tasty pizza and snacks, this event is for you. We look forward to seeing you on Tuesday the 18th of June!

This session’s speakers are Fatima Khan and Carmen Domínguez, 2nd year Master in Neuroscience VU students.

[Register](https://vu-nl.libcal.com/event/4216258)


# Featured TidyTuesday Dataset 

Would you like to practice your coding skills and experiment with others (or individually) with a real dataset that is (probably) not related to your research project? We select a featured dataset from the [TidyTuesday](https://github.com/rfordatascience/tidytuesday) Data Science Learning challenge that you can analyze during the event. Ask for help if you get stuck and practice your data analysis skills.

Talking about Pizza, how often do you wonder about science around **cheese**?

> This week's dataset is all about cheese: [Dataset of the week](https://github.com/rfordatascience/tidytuesday/tree/master/data/2024/2024-06-04)

The data this week comes from [cheese.com](https://www.cheese.com).

Cheese is nutritious food made mostly from the milk of cows but also other mammals, including sheep, goats, buffalo, reindeer, camels and yaks. Around 4000 years ago people have started to breed animals and process their milk. That's when the cheese was born.
Explore this site to find out about different kinds of cheese from all around the world.

248 cheeses have listed fat content. 

* Is there a relationship between fat content and cheese type? 
* What about texture, flavor, or aroma? 
> Blockquote
